spring.application.name=patent

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.profiles.default=local

app.jwt.secret=${JWT_SECRET:change-me}
app.jwt.expiration-seconds=${JWT_EXP_SECONDS:86400}
